import Image from "next/image";
import Link from "next/link";
import { BrandLockup } from "@/components/brand";
import { PricingFaqs, PricingTiers } from "@/components/PricingTiers";

const APP_STORE_URL = "https://apps.apple.com/us/app/responder-roadmap/id6800092347";
const steps = [
  { number: "01", title: "Build & assign", detail: "Create a Task Book or import an existing PDF. Review and publish the version your department will use." },
  { number: "02", title: "Evaluate in the field", detail: "Members submit their work. Evaluators document skills and return attempts that need remediation." },
  { number: "03", title: "Approve & retain", detail: "Complete required approvals and preserve versioned records, reviewer decisions, and progress." },
];
const faqs = [
  ["Can we bring our existing Task Book?", "Yes. Import a PDF into a draft, then have a Training Officer review and edit it before publishing."],
  ["Does completing a checklist automatically count?", "No. A requirement counts only after its required approvals are completed."],
  ["Can members use an iPhone?", "Yes. Members have access to the iPhone app. The screenshots on this page were captured from the real web demo, including its mobile-web views."],
  ["What if we already have an LMS?", "Responder Roadmap focuses on Task Books, field evaluations, approvals, and training records. You can keep your existing course platform."],
];

function Ctas({ demoHref, centered = false }: { demoHref: string; centered?: boolean }) {
  return <div className={`flex flex-col gap-3 sm:flex-row ${centered ? "sm:justify-center" : ""}`}>
    <Link href={demoHref} className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#E11D48] px-6 py-3 text-center text-sm font-bold text-white shadow-lg shadow-rose-950/25 transition hover:bg-[#BE123C]">{demoHref === "/demo" ? "Explore the live demo" : "Request a department demo"} →</Link>
    <Link href="/register" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-white/30 bg-white/5 px-6 py-3 text-center text-sm font-bold text-white transition hover:bg-white/10">Start free <span className="ml-2 font-normal text-white/65">0–5 members</span></Link>
  </div>;
}

function ProductPreview({ demoHref }: { demoHref: string }) {
  return <div className="relative mx-auto w-full max-w-[690px] pb-12 pr-7 sm:pb-16 sm:pr-12" aria-label="Actual Responder Roadmap demo screenshots from desktop and mobile web">
    <div className="overflow-hidden rounded-2xl border border-white/20 bg-[#111D2F] shadow-[0_35px_100px_rgba(0,0,0,.5)]">
      <div className="flex items-center justify-between gap-2 border-b border-white/10 bg-[#15243A] px-4 py-3 text-[11px] font-semibold text-white/75"><span>Training Officer dashboard</span><span className="shrink-0 rounded-full bg-emerald-400/10 px-2 py-1 text-emerald-200">Actual demo screen</span></div>
      <Image src="/showcase/dashboard-demo.png" alt="Actual Responder Roadmap Metro Fire demo dashboard" width={1440} height={900} priority sizes="(max-width: 1024px) 92vw, 690px" className="h-auto w-full" />
      <div className="flex flex-wrap items-center justify-between gap-2 border-t border-white/10 px-4 py-3 text-[11px] text-white/55"><span>Metro Fire · Fictional demo records</span><Link href={demoHref} className="font-bold text-[#FDA4AF] underline">Explore this screen →</Link></div>
    </div>
    <div className="absolute bottom-0 right-0 w-[32%] max-w-[202px] overflow-hidden rounded-[1.5rem] border-[5px] border-[#28364C] bg-[#0B1220] shadow-[0_25px_65px_rgba(0,0,0,.65)] sm:w-[29%]" aria-label="Member mobile web demo screenshot">
      <div className="mx-auto my-1.5 h-1 w-9 rounded-full bg-white/30" />
      <Image src="/showcase/member-demo.png" alt="Actual member Task Books mobile-web demo" width={390} height={844} priority sizes="(max-width: 640px) 32vw, 202px" className="block h-auto w-full" />
    </div>
    <p className="mt-3 max-w-[75%] text-xs leading-5 text-white/45">Real web demo screenshots. The phone frame shows the mobile website, not the native app.</p>
  </div>;
}

export function LandingPage({ demoAvailable }: { demoAvailable: boolean }) {
  const demoHref = demoAvailable ? "/demo" : "/department-interest?source=demo-unavailable";
  return <div className="min-h-screen overflow-x-hidden bg-[#0B1220] text-white">
    <header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link href="/" aria-label="Responder Roadmap home"><BrandLockup size={40} subtitle="Fire & EMS Training Management" /></Link><nav aria-label="Main navigation" className="order-3 flex w-full items-center justify-between gap-4 text-sm font-semibold text-white/70 sm:order-none sm:w-auto sm:gap-6"><Link href={demoHref} className="hover:text-white">Demo</Link><a href="#product" className="hover:text-white">Product</a><a href="#pricing" className="hover:text-white">Pricing</a><Link href="/login" className="hover:text-white">Sign in</Link></nav><Link href={demoHref} className="hidden min-h-10 items-center rounded-lg bg-[#E11D48] px-4 text-sm font-bold lg:inline-flex">Explore demo →</Link></div></header>
    <main>
      <section className="relative isolate overflow-hidden"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-16 pt-16 sm:px-8 lg:grid-cols-[.88fr_1.12fr] lg:pb-24 lg:pt-24"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#FB7185]">Digital Task Books for Fire & EMS</p><h1 className="mt-5 max-w-2xl text-4xl font-extrabold leading-[1.07] tracking-[-.045em] sm:text-5xl lg:text-[3.55rem]">Digital Task Books.<br /><span className="text-[#FB7185]">Clear progress.</span><br />Verified sign-offs.</h1><p className="mt-6 max-w-xl text-base leading-8 text-white/70 sm:text-lg">Create and assign Task Books, evaluate skills in the field, and track every member’s progress from one department dashboard.</p><div className="mt-8"><Ctas demoHref={demoHref} /></div><p className="mt-4 text-sm text-white/50">Explore the demo without signing up. Free for up to five active members.</p><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-white/60"><span>✓ Field evaluations</span><span>✓ Approval history</span><span>✓ Versioned records</span></div></div><ProductPreview demoHref={demoHref} /></div></section>
      <section className="border-y border-white/10 bg-[#101B2C]"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-12 gap-y-3 px-5 py-5 text-center text-sm font-semibold text-white/60 sm:justify-between sm:px-8"><span>Built for the way Fire & EMS departments train.</span><span>Free plan available</span><span>Department-owned records</span></div></section>
      <section id="product" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">See the actual software</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Built for the desk. Ready for the field.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-white/65">Explore real screens captured from our fictional Metro Fire demo. These show the working web portal, not generic mockups.</p><div className="mt-10 grid items-center gap-8 lg:grid-cols-[1.4fr_.6fr]"><div className="overflow-hidden rounded-2xl border border-white/15 bg-[#111D2F]"><Image src="/showcase/dashboard-demo.png" alt="Training Officer department overview in the fictional Metro Fire demo" width={1440} height={900} sizes="(max-width: 1024px) 95vw, 780px" className="h-auto w-full" /></div><div className="space-y-5"><div className="rounded-xl border border-white/15 bg-[#111D2F] p-5"><p className="text-xs font-bold uppercase tracking-widest text-[#FB7185]">01 / See what needs attention</p><h3 className="mt-2 text-xl font-bold">An actionable daily overview</h3><p className="mt-2 text-sm leading-7 text-white/60">Open assignments, follow up on outstanding work, and see Task Book progress.</p></div><div className="rounded-xl border border-white/15 bg-[#111D2F] p-5"><p className="text-xs font-bold uppercase tracking-widest text-[#FB7185]">02 / Keep the record</p><h3 className="mt-2 text-xl font-bold">Approvals stay documented</h3><p className="mt-2 text-sm leading-7 text-white/60">Review history and final approval determine what counts as completed training.</p></div></div></div><div className="mt-10 grid gap-6 rounded-2xl border border-white/10 bg-[#111D2F] p-5 sm:p-8 md:grid-cols-2 md:items-center"><div><p className="text-xs font-bold uppercase tracking-widest text-[#FB7185]">Mobile web · Member & evaluator</p><h3 className="mt-3 text-2xl font-bold">One workflow across your team.</h3><p className="mt-4 text-sm leading-7 text-white/65">Members see assignments and evaluators open their queues on mobile. The images are mobile-web screenshots, not native app screenshots.</p><a href={APP_STORE_URL} target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 items-center text-sm font-bold text-[#FDA4AF] underline">Get the iPhone app ↗</a></div><div className="flex justify-center gap-4"><Image src="/showcase/member-demo.png" alt="Member mobile-web demo" width={160} height={347} sizes="160px" className="h-auto w-[44%] max-w-[160px] rounded-xl border-4 border-[#28364C]" /><Image src="/showcase/evaluator-demo.png" alt="Evaluator mobile-web demo" width={160} height={347} sizes="160px" className="h-auto w-[44%] max-w-[160px] rounded-xl border-4 border-[#28364C]" /></div></div></section>
      <section id="how-it-works" className="border-y border-white/10 bg-[#101B2C]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">One connected workflow</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">From assignment to approved training record.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{steps.map((step) => <article key={step.number} className="rounded-2xl border border-white/10 bg-[#111D2F] p-6"><span className="text-sm font-bold text-[#FB7185]">{step.number}</span><h3 className="mt-5 text-xl font-bold">{step.title}</h3><p className="mt-3 text-sm leading-7 text-white/60">{step.detail}</p></article>)}</div><p className="mt-6 rounded-lg border border-[#E11D48]/30 bg-[#E11D48]/10 px-5 py-4 text-sm leading-6 text-white/80"><strong className="text-white">Approval is the gate.</strong> A member’s submission does not count until every required approval is recorded.</p></div></section>
      <section id="security" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">Training records you can review</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Document the decision, not just the checkbox.</h2><p className="mt-5 max-w-3xl leading-8 text-white/65">Keep submissions, evaluator decisions, remediation notes, version history, and final approvals together. Access to management and sign-offs depends on department permissions.</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Documented evaluator decisions", "Versioned assignments", "Remediation and attempt history", "Reports and printable records"].map((feature) => <div key={feature} className="rounded-xl border border-white/10 bg-[#111D2F] px-5 py-5 text-sm font-semibold text-white/75">✓ {feature}</div>)}</div></section>
      <PricingTiers id="pricing" />
      <section className="mx-auto max-w-5xl px-5 pt-20 sm:px-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">Frequently asked questions</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Answers before you start.</h2><div className="mt-9 divide-y divide-white/10 border-y border-white/10">{faqs.map(([question, answer]) => <details key={question} className="py-5"><summary className="cursor-pointer font-semibold">{question}</summary><p className="mt-3 text-sm leading-7 text-white/65">{answer}</p></details>)}</div></section>
      <PricingFaqs />
      <section className="border-t border-white/10 bg-[#101B2C] px-5 py-20 text-center sm:py-24"><p className="text-xs font-bold uppercase tracking-widest text-[#FB7185]">See it in action</p><h2 className="mx-auto mt-4 max-w-3xl text-3xl font-bold tracking-tight sm:text-4xl">Ready to move beyond the binder?</h2><p className="mx-auto mb-8 mt-4 max-w-xl leading-7 text-white/65">Explore the full department workflow with fictional records, or start with a small crew for free.</p><Ctas demoHref={demoHref} centered /><p className="mt-5 text-sm text-white/45">Already invited? <Link href="/login" className="font-semibold text-white underline">Sign in</Link></p></section>
    </main>
    <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-8 text-sm text-white/50 sm:px-8 md:flex-row"><div><p className="font-bold text-white/80">Responder Roadmap · Department Task Books</p><p className="mt-1">Fire · EMS · Training Division</p><p className="mt-3 text-xs">Practice in FireOpsSim. Official completion in Responder Roadmap.</p></div><div className="flex flex-wrap gap-5"><Link href="/login" className="hover:text-white">Sign in</Link><a href="#security" className="hover:text-white">Training records</a><a href={APP_STORE_URL} target="_blank" rel="noreferrer" className="hover:text-white">iPhone app</a><Link href="/pricing" className="hover:text-white">Pricing</Link><Link href="/department-interest" className="hover:text-white">Contact</Link></div></div></footer>
  </div>;
}
