import Link from "next/link";
import { BrandLockup } from "@/components/brand";

const APP_STORE_URL = "https://apps.apple.com/us/app/responder-roadmap/id6800092347";
const steps = [
  { number: "01", title: "Build & assign", detail: "Create a Task Book or import your existing PDF. Assign the approved version to the right members." },
  { number: "02", title: "Evaluate in the field", detail: "Collect submissions, document attempts, and return work for remediation when needed." },
  { number: "03", title: "Approve & retain", detail: "Record the required approvals, preserve the history, and report on verified progress." },
];
const faqs = [
  ["Can we bring our existing Task Book?", "Yes. Import a PDF into a draft, then have a Training Officer review and edit it before publishing."],
  ["Does completing a checklist automatically count?", "No. A requirement counts only after its required approvals are completed."],
  ["Can our members use an iPhone?", "Yes. The iPhone app supports members in the field, while the web portal manages the department workflow."],
  ["What if we already have an LMS?", "Responder Roadmap focuses on Task Books, field evaluations, approvals, and training records. You can keep your existing course platform."],
];

function Ctas({ demoHref, centered = false }: { demoHref: string; centered?: boolean }) {
  return (
    <div className={`flex flex-col gap-3 sm:flex-row ${centered ? "sm:justify-center" : ""}`}>
      <Link href={demoHref} className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#E11D48] px-6 py-3 text-center text-sm font-bold text-white shadow-lg shadow-rose-950/25 transition hover:bg-[#BE123C] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">{demoHref === "/demo" ? "Explore the 3-minute demo" : "Request a department demo"} <span aria-hidden="true" className="ml-2">→</span></Link>
      <Link href="/register" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-white/30 bg-white/5 px-6 py-3 text-center text-sm font-bold text-white transition hover:bg-white/10">Start free <span className="ml-2 font-normal text-white/65">0–5 members</span></Link>
    </div>
  );
}

function ProductPreview({ demoHref }: { demoHref: string }) {
  return (
    <div className="relative mx-auto w-full max-w-[640px] pb-12 sm:pr-10 lg:pb-16" aria-label="Illustrative Responder Roadmap desktop and mobile workflow">
      <div className="overflow-hidden rounded-2xl border border-white/20 bg-[#111D2F] shadow-[0_35px_100px_rgba(0,0,0,.5)]">
        <div className="flex items-center justify-between border-b border-white/10 bg-[#15243A] px-4 py-3 text-xs text-white/65"><span className="font-bold text-white">Responder Roadmap <span className="font-normal text-white/45">/ Home</span></span><span className="rounded-full bg-white/10 px-2 py-1">Training Officer</span></div>
        <div className="p-4 sm:p-6">
          <p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#FB7185]">Department overview</p>
          <h2 className="mt-1 text-xl font-bold tracking-tight sm:text-2xl">Who needs you today?</h2>
          <div className="mt-5 grid grid-cols-3 gap-2 sm:gap-3">
            {[["Pending reviews", "3"], ["Due soon", "2"], ["Active books", "8"]].map(([label, value]) => <div key={label} className="rounded-lg border border-white/10 bg-[#0B1220] p-2 sm:p-3"><p className="text-[10px] leading-4 text-white/55 sm:text-xs">{label}</p><p className="mt-1 text-xl font-bold sm:text-3xl">{value}</p></div>)}
          </div>
          <div className="mt-4 overflow-hidden rounded-xl border border-white/10">
            <div className="flex justify-between bg-white/5 px-3 py-3 text-xs font-bold"><span>Task Book progress</span><span className="text-white/50">Illustrative data</span></div>
            {[["Jordan S.", "Probationary firefighter", "72%"], ["Chris T.", "Driver / Operator", "41%"], ["Taylor B.", "Probationary firefighter", "90%"]].map(([name, role, progress]) => <div key={name} className="flex items-center gap-3 border-t border-white/10 px-3 py-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#263A5E] text-xs font-bold">{name.charAt(0)}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold sm:text-sm">{name}</p><p className="truncate text-[10px] text-white/45">{role}</p></div><span className="text-xs font-bold text-white/80">{progress}</span></div>)}
          </div>
        </div>
        <div className="flex items-center justify-between gap-3 border-t border-white/10 px-4 py-3 text-[11px] text-white/45"><span>Illustrative interface · Not a live screenshot</span><Link href={demoHref} className="shrink-0 font-bold text-[#FDA4AF] underline underline-offset-4">Open real demo →</Link></div>
      </div>
      <div className="absolute -bottom-1 right-0 w-[39%] min-w-[128px] max-w-[205px] overflow-hidden rounded-[1.6rem] border-[5px] border-[#27364C] bg-[#0B1220] shadow-[0_25px_65px_rgba(0,0,0,.65)] sm:bottom-0">
        <div className="mx-auto mt-2 h-1 w-10 rounded-full bg-white/25" />
        <div className="px-3 pb-5 pt-5"><p className="text-[10px] font-bold text-white/50">FIELD REVIEW</p><h3 className="mt-2 text-sm font-bold leading-tight">Attack line deployment</h3><p className="mt-2 text-[10px] text-white/55">Submitted for evaluation</p><div className="mt-4 rounded-lg border border-white/15 bg-white/5 p-2 text-[10px] text-white/70">Requirement checklist<br /><span className="mt-2 block text-[#86EFAC]">✓ Assessment recorded</span><span className="mt-1 block text-[#86EFAC]">✓ Evidence attached</span></div><div className="mt-4 rounded-md bg-[#E11D48] px-2 py-2 text-center text-[10px] font-bold">Review submission</div></div>
      </div>
    </div>
  );
}

function Price({ title, price, term, description, bullets, href, cta, featured = false }: { title: string; price: string; term?: string; description: string; bullets: string[]; href: string; cta: string; featured?: boolean }) {
  return <article className={`flex h-full flex-col rounded-2xl border p-6 sm:p-7 ${featured ? "border-[#E11D48] bg-[#172236] shadow-[0_25px_70px_rgba(0,0,0,.25)]" : "border-white/15 bg-[#111D2F]"}`}>
    <p className="text-sm font-bold text-[#FDA4AF]">{title}</p><div className="mt-3 flex items-baseline gap-1"><span className="text-4xl font-bold tracking-tight">{price}</span>{term ? <span className="text-sm text-white/50">{term}</span> : null}</div><p className="mt-2 text-sm text-white/60">{description}</p><ul className="my-7 flex-1 space-y-3">{bullets.map(bullet => <li key={bullet} className="flex gap-2 text-sm text-white/75"><span className="text-[#FDA4AF]" aria-hidden="true">✓</span>{bullet}</li>)}</ul><Link href={href} className={`inline-flex min-h-12 items-center justify-center rounded-lg px-4 py-3 text-center text-sm font-bold transition ${featured ? "bg-[#E11D48] hover:bg-[#BE123C]" : "border border-white/25 hover:bg-white/10"}`}>{cta}</Link>
  </article>;
}

export function LandingPage({ demoAvailable }: { demoAvailable: boolean }) {
  const demoHref = demoAvailable ? "/demo" : "/department-interest?source=demo-unavailable";
  return (
    <div className="min-h-screen overflow-x-hidden bg-[#0B1220] text-white">
      <header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link href="/" aria-label="Responder Roadmap home"><BrandLockup size={40} subtitle="Fire & EMS Training Management" /></Link><nav aria-label="Main navigation" className="order-3 flex w-full items-center justify-between gap-4 text-sm font-semibold text-white/70 sm:order-none sm:w-auto sm:gap-6"><Link href={demoHref} className="hover:text-white">Demo</Link><a href="#how-it-works" className="hover:text-white">How it works</a><a href="#pricing" className="hover:text-white">Pricing</a><Link href="/login" className="hover:text-white">Sign in</Link></nav><Link href={demoHref} className="hidden min-h-10 items-center rounded-lg bg-[#E11D48] px-4 text-sm font-bold transition hover:bg-[#BE123C] lg:inline-flex">Explore demo →</Link></div></header>
      <main>
        <section className="relative isolate overflow-hidden"><div aria-hidden="true" className="pointer-events-none absolute -right-40 -top-48 -z-10 h-[680px] w-[680px] rounded-full bg-[#E11D48]/[.075] blur-[110px]" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-16 pt-16 sm:px-8 lg:grid-cols-[.95fr_1.05fr] lg:gap-16 lg:pb-24 lg:pt-24"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#FB7185]">Digital Task Books for Fire & EMS</p><h1 className="mt-5 max-w-2xl text-4xl font-extrabold leading-[1.07] tracking-[-.045em] sm:text-5xl lg:text-[3.65rem]">Digital Task Books.<br /><span className="text-[#FB7185]">Clear progress.</span><br />Verified sign-offs.</h1><p className="mt-6 max-w-xl text-base leading-8 text-white/70 sm:text-lg">Create and assign Task Books, evaluate skills in the field, and track every member’s progress from one department dashboard.</p><div className="mt-8"><Ctas demoHref={demoHref} /></div><p className="mt-4 text-sm text-white/50">Explore the demo without signing up. Free for up to five active members.</p><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-white/60"><span>✓ Field evaluations</span><span>✓ Approval history</span><span>✓ Versioned records</span></div></div><ProductPreview demoHref={demoHref} /></div></section>
        <section className="border-y border-white/10 bg-[#101B2C]"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-12 gap-y-3 px-5 py-5 text-center text-sm font-semibold text-white/60 sm:justify-between sm:px-8"><span>Built for the way Fire & EMS departments train.</span><span>Free plan available</span><span>Department-owned records</span></div></section>
        <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">One connected workflow</p><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><h2 className="max-w-3xl text-3xl font-bold tracking-tight sm:text-4xl">From assignment to approved training record.</h2><Link href={demoHref} className="text-sm font-semibold text-[#FDA4AF] underline underline-offset-4">See the workflow in the demo →</Link></div><div className="mt-10 grid gap-4 md:grid-cols-3">{steps.map(step => <article key={step.number} className="rounded-2xl border border-white/10 bg-[#111D2F] p-6"><span className="text-sm font-bold tracking-widest text-[#FB7185]">{step.number}</span><h3 className="mt-5 text-xl font-bold">{step.title}</h3><p className="mt-3 text-sm leading-7 text-white/60">{step.detail}</p></article>)}</div><p className="mt-6 rounded-lg border border-[#E11D48]/30 bg-[#E11D48]/10 px-5 py-4 text-sm leading-6 text-white/80"><strong className="text-white">Approval is the gate.</strong> A member’s submission does not count as complete until every required approval is recorded.</p></section>
        <section className="border-y border-white/10 bg-[#101B2C]"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">Desk + field</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Your training workflow, without the binder hunt.</h2><p className="mt-5 max-w-xl leading-8 text-white/65">Training Officers can assign work and spot delays. Evaluators can review field submissions. Members can see exactly what is still waiting.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Task Book library & PDF-assisted drafts", "Class rosters & proctor tools", "Evaluation and remediation history", "Progress reports & exports"].map(feature => <div key={feature} className="rounded-lg border border-white/10 bg-white/[.035] p-4 text-sm font-medium text-white/80"><span className="mr-2 text-[#FB7185]" aria-hidden="true">✓</span>{feature}</div>)}</div></div><div className="overflow-hidden rounded-2xl border border-white/15 bg-[#0B1220] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-widest text-[#FB7185]">Official record workflow</p><div className="mt-7 space-y-4">{["Training Officer publishes the reviewed version", "Member submits work and evidence", "Evaluator signs or returns for remediation", "Required final approval updates verified progress"].map((item, index) => <div key={item} className="flex items-center gap-4 rounded-xl border border-white/10 bg-white/[.04] p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#E11D48]/20 text-sm font-bold text-[#FDA4AF]">{index + 1}</span><span className="text-sm leading-6 text-white/80">{item}</span></div>)}</div><p className="mt-5 text-xs leading-6 text-white/45">Every sign-off remains linked to its Task Book version and recorded review history.</p></div></div></section>
        <section id="security" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">Trust the training record</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Document the decision, not just the checkbox.</h2><p className="mt-5 leading-8 text-white/65">Keep submitted work, evaluator decisions, remediation notes, version history, and final approvals together. Roles limit who can manage members and authorize evaluations.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Versioned Task Books", "Documented sign-offs", "Role-based permissions", "Exportable history"].map(item => <div key={item} className="rounded-xl border border-white/15 bg-[#111D2F] p-5 text-sm font-semibold"><span className="mr-2 text-[#FDA4AF]">✓</span>{item}</div>)}</div></section>
        <section id="pricing" className="border-y border-white/10 bg-[#101B2C]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">Straightforward pricing</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Start with your crew. Grow with your department.</h2><p className="mt-4 max-w-2xl text-white/60">Plans are based on active members. See what fits before requesting a quote.</p><div className="mt-10 grid gap-5 lg:grid-cols-3"><Price title="Free" price="$0" description="Up to 5 active members" bullets={["Full Task Book workflow", "No payment card required", "Ideal for a crew or trial"]} href="/register" cta="Start free" /><Price featured title="Founding" price="$500" term="/ year" description="Up to 75 active members" bullets={["Unlimited Task Books", "Evaluators and department admins", "No setup fee", "Founding price while subscribed"]} href="/department-interest?plan=founding" cta="Ask about the founding plan" /><Price title="Department" price="Custom" description="76+ active members" bullets={["Department-scale setup", "Rosters, Task Books, and reports", "Request an invoice or purchase order"]} href="/department-interest?plan=department" cta="Contact for pricing" /></div><p className="mt-6 text-xs leading-6 text-white/50">The iPhone app supports personal career records. Official department sign-off is part of the department workflow.</p></div></section>
        <section className="mx-auto max-w-4xl px-5 py-20 sm:px-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">Frequently asked</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Answers before you start.</h2><div className="mt-8 divide-y divide-white/10 border-y border-white/10">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex min-h-9 cursor-pointer list-none items-center justify-between gap-4 font-semibold"><span>{question}</span><span aria-hidden="true" className="text-[#FB7185] group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-7 text-white/60">{answer}</p></details>)}</div></section>
        <section className="border-t border-white/10 bg-[#111D2F] px-5 py-20 text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FB7185]">Ready to see how it works?</p><h2 className="mx-auto mt-4 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">Put your department’s training in one place.</h2><p className="mx-auto mb-8 mt-4 max-w-xl text-white/60">Explore a sample department or get started with up to five members for free.</p><Ctas demoHref={demoHref} centered /></section>
      </main>
      <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-5 py-8 text-sm text-white/55 sm:px-8 lg:flex-row"><div><p className="font-bold text-white">Responder Roadmap</p><p className="mt-1 text-xs">Fire & EMS training management</p><a className="mt-3 inline-block text-xs underline underline-offset-4 hover:text-white" href={APP_STORE_URL} target="_blank" rel="noreferrer">Download the iPhone app ↗</a></div><nav aria-label="Footer" className="flex flex-wrap items-start gap-5"><Link href="/login" className="hover:text-white">Sign in</Link><a href="#security" className="hover:text-white">Training records</a><a href="#pricing" className="hover:text-white">Pricing</a><Link href="/department-interest" className="hover:text-white">Contact</Link></nav></div></footer>
    </div>
  );
}
